security:
  basic:
    enabled: false

management:
  security:
    enabled: false

# my laptop is slow... delay hystrix kick-in for local tests
#hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 60000